user:
  outputs:
    default:
      account: RDA19741.east-us-2.azure
      auth_type: password
      client_session_keep_alive: false
      connect_retries: 3
      connect_timeout: 30
      database: analytics
      password: Rhw3zvaRqU;,Y-5
      retry_on_database_errors: true
      role: PC_DBT_ROLE
      schema: dbt_tmorlock
      type: snowflake
      user: tmorlocksyr
      warehouse: transforming
  target: default
